// Mock Customer type to replace deleted service
interface Customer {
  id: string;
  name: string;
  email: string;
  phone?: string;
  companyName?: string;
  type: 'business' | 'business-owner' | 'asset-seller' | 'broker-originator' | 'service-provider';
  status: 'active' | 'inactive' | 'pending';
  dateAdded: string;
  lastContact?: string;
  customerScore?: number;
  avatar?: string;
  assignedTo?: string;
  notes?: string;
  industry?: string;
  tags?: string[];
}

// Mock data for customer entities
const mockCustomers: Customer[] = [
  {
    id: 'cust-001',
    name: 'Acme Corporation',
    email: 'info@acmecorp.com',
    phone: '+15551234567',
    companyName: 'Acme Corporation',
    type: 'business',
    status: 'active',
    dateAdded: '2023-01-15T10:30:00Z',
    lastContact: '2023-04-28T14:15:00Z',
    customerScore: 85,
    avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
    assignedTo: 'user-003',
    notes: 'Key account, interested in equipment financing.',
    industry: 'Manufacturing',
    tags: ['key-account', 'manufacturing', 'equipment-financing'],
  },
  {
    id: 'cust-002',
    name: 'TechSolutions Inc',
    email: 'contact@techsolutions.io',
    phone: '+15552345678',
    companyName: 'TechSolutions Inc',
    type: 'business',
    status: 'active',
    dateAdded: '2023-02-02T09:45:00Z',
    lastContact: '2023-04-15T11:20:00Z',
    customerScore: 72,
    avatar: 'https://randomuser.me/api/portraits/men/2.jpg',
    assignedTo: 'user-002',
    notes: 'Growing tech company, looking for expansion capital.',
    industry: 'Technology',
    tags: ['tech', 'growing', 'expansion'],
  },
  {
    id: 'cust-003',
    name: 'Green Valley Organics',
    email: 'hello@greenvalley.com',
    phone: '+15553456789',
    companyName: 'Green Valley Organics',
    type: 'business',
    status: 'active',
    dateAdded: '2023-02-10T16:15:00Z',
    lastContact: '2023-04-22T13:45:00Z',
    customerScore: 68,
    avatar: 'https://randomuser.me/api/portraits/women/3.jpg',
    assignedTo: 'user-004',
    notes: 'Organic food producer, interested in sustainable financing options.',
    industry: 'Agriculture',
    tags: ['agriculture', 'organic', 'sustainable'],
  },
  {
    id: 'cust-004',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@email.com',
    phone: '+15554567890',
    type: 'business-owner',
    status: 'active',
    dateAdded: '2023-02-15T11:30:00Z',
    lastContact: '2023-04-10T10:00:00Z',
    customerScore: 91,
    avatar: 'https://randomuser.me/api/portraits/women/4.jpg',
    assignedTo: 'user-001',
    notes: 'Owner of Johnson\'s Hardware Store, looking for acquisition financing.',
    industry: 'Retail',
    tags: ['retail', 'expansion', 'acquisition'],
  },
  {
    id: 'cust-005',
    name: 'Michael Chang',
    email: 'michael@changindustries.com',
    phone: '+15555678901',
    companyName: 'Chang Industries',
    type: 'business-owner',
    status: 'active',
    dateAdded: '2023-02-20T14:20:00Z',
    lastContact: '2023-04-05T15:30:00Z',
    customerScore: 77,
    avatar: 'https://randomuser.me/api/portraits/men/5.jpg',
    assignedTo: 'user-002',
    notes: 'Owns multiple businesses, interested in refinancing.',
    industry: 'Various',
    tags: ['multi-business', 'refinancing'],
  },
  {
    id: 'cust-006',
    name: 'Reliable Equipment Sales',
    email: 'sales@reliableequip.com',
    phone: '+15556789012',
    companyName: 'Reliable Equipment Sales',
    type: 'asset-seller',
    status: 'active',
    dateAdded: '2023-03-05T08:45:00Z',
    lastContact: '2023-04-28T09:15:00Z',
    customerScore: 82,
    avatar: 'https://randomuser.me/api/portraits/men/6.jpg',
    assignedTo: 'user-003',
    notes: 'Sells construction equipment, interested in partnership options.',
    industry: 'Construction',
    tags: ['equipment', 'construction', 'partnership'],
  },
  {
    id: 'cust-007',
    name: 'Robert Fisher',
    email: 'robert.fisher@premierlending.com',
    phone: '+15557890123',
    companyName: 'Premier Lending Solutions',
    type: 'broker-originator',
    status: 'active',
    dateAdded: '2023-03-10T10:30:00Z',
    lastContact: '2023-04-26T14:00:00Z',
    customerScore: 95,
    avatar: 'https://randomuser.me/api/portraits/men/7.jpg',
    assignedTo: 'user-004',
    notes: 'Broker with extensive network, high potential for deals.',
    industry: 'Finance',
    tags: ['broker', 'high-performer', 'finance'],
  },
  {
    id: 'cust-008',
    name: 'Laura Martinez',
    email: 'laura@businessadvisors.com',
    phone: '+15558901234',
    companyName: 'Martinez Business Advisors',
    type: 'service-provider',
    status: 'active',
    dateAdded: '2023-03-15T13:15:00Z',
    lastContact: '2023-04-20T11:45:00Z',
    customerScore: 88,
    avatar: 'https://randomuser.me/api/portraits/women/8.jpg',
    assignedTo: 'user-001',
    notes: 'Business consultant, good referral source.',
    industry: 'Consulting',
    tags: ['consultant', 'referrals', 'business-advisory'],
  },
  {
    id: 'cust-009',
    name: 'Quick Logistics',
    email: 'info@quicklogistics.com',
    phone: '+15559012345',
    companyName: 'Quick Logistics',
    type: 'business',
    status: 'inactive',
    dateAdded: '2023-03-20T09:00:00Z',
    lastContact: '2023-03-25T16:30:00Z',
    customerScore: 45,
    avatar: 'https://randomuser.me/api/portraits/men/9.jpg',
    assignedTo: 'user-002',
    notes: 'Transportation company, currently inactive due to restructuring.',
    industry: 'Transportation',
    tags: ['logistics', 'transportation', 'restructuring'],
  },
  {
    id: 'cust-010',
    name: 'James Wilson',
    email: 'james@wilsonproperties.com',
    phone: '+15550123456',
    companyName: 'Wilson Properties',
    type: 'business-owner',
    status: 'pending',
    dateAdded: '2023-04-01T11:45:00Z',
    customerScore: 65,
    avatar: 'https://randomuser.me/api/portraits/men/10.jpg',
    assignedTo: 'user-003',
    notes: 'Real estate developer, interested in property financing.',
    industry: 'Real Estate',
    tags: ['real-estate', 'property-development'],
  },
  {
    id: 'cust-011',
    name: 'Modern Office Solutions',
    email: 'sales@modernoffice.com',
    phone: '+15551122334',
    companyName: 'Modern Office Solutions',
    type: 'business',
    status: 'active',
    dateAdded: '2023-04-05T14:30:00Z',
    lastContact: '2023-04-25T10:15:00Z',
    customerScore: 73,
    avatar: 'https://randomuser.me/api/portraits/women/11.jpg',
    assignedTo: 'user-004',
    notes: 'Office furniture and equipment supplier, exploring inventory financing.',
    industry: 'Retail',
    tags: ['office-equipment', 'inventory-financing'],
  },
  {
    id: 'cust-012',
    name: 'Advanced Manufacturing Inc',
    email: 'info@advmfg.com',
    phone: '+15552233445',
    companyName: 'Advanced Manufacturing Inc',
    type: 'business',
    status: 'active',
    dateAdded: '2023-04-10T09:15:00Z',
    lastContact: '2023-04-27T15:45:00Z',
    customerScore: 81,
    avatar: 'https://randomuser.me/api/portraits/men/12.jpg',
    assignedTo: 'user-001',
    notes: 'Precision manufacturing company, planning equipment upgrades.',
    industry: 'Manufacturing',
    tags: ['manufacturing', 'equipment-financing', 'high-tech'],
  },
  {
    id: 'cust-013',
    name: 'Elite Financial Partners',
    email: 'contact@elitefinancial.com',
    phone: '+15553344556',
    companyName: 'Elite Financial Partners',
    type: 'broker-originator',
    status: 'active',
    dateAdded: '2023-04-15T13:00:00Z',
    lastContact: '2023-04-28T09:30:00Z',
    customerScore: 90,
    avatar: 'https://randomuser.me/api/portraits/women/13.jpg',
    assignedTo: 'user-002',
    notes: 'Financial brokerage specializing in commercial lending.',
    industry: 'Finance',
    tags: ['finance', 'brokerage', 'commercial-lending'],
  },
  {
    id: 'cust-014',
    name: 'Sunrise Bakery',
    email: 'hello@sunrisebakery.com',
    phone: '+15554455667',
    companyName: 'Sunrise Bakery',
    type: 'business',
    status: 'pending',
    dateAdded: '2023-04-20T10:45:00Z',
    customerScore: 62,
    avatar: 'https://randomuser.me/api/portraits/women/14.jpg',
    assignedTo: 'user-003',
    notes: 'Local bakery chain, exploring expansion financing.',
    industry: 'Food & Beverage',
    tags: ['food', 'bakery', 'expansion'],
  },
  {
    id: 'cust-015',
    name: 'Patricia Lee',
    email: 'patricia@leeaccounting.com',
    phone: '+15555566778',
    companyName: 'Lee Accounting Services',
    type: 'service-provider',
    status: 'active',
    dateAdded: '2023-04-25T15:30:00Z',
    lastContact: '2023-04-26T11:00:00Z',
    customerScore: 85,
    avatar: 'https://randomuser.me/api/portraits/women/15.jpg',
    assignedTo: 'user-004',
    notes: 'Accounting firm, potential source for client referrals.',
    industry: 'Accounting',
    tags: ['accounting', 'professional-services', 'referrals'],
  },
];

export default mockCustomers; 