version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: auto
    reviewers:
      - "financeaiguy"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "deps"
      include: "scope"
    ignore:
      # Ignore updates to packages that start with 'aws'
      # - dependency-name: "aws-*"
      # Ignore some updates to the package
      # - dependency-name: "express"
      #   versions: ["4.x", "5.x"] 