name: Branch Naming Convention

on:
  push:
    branches-ignore:
      - main
      - master
      - develop
      - staging
      - release/*

jobs:
  branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          VALID_PREFIXES="feature|bugfix|hotfix|release|chore|docs|refactor|test|ci|build"
          
          if ! [[ $BRANCH_NAME =~ ^($VALID_PREFIXES)/.+ ]]; then
            echo "::error::Branch name '$BRANCH_NAME' does not follow the naming convention: $VALID_PREFIXES/descriptive-name"
            exit 1
          fi
          
          echo "Branch '$BRANCH_NAME' follows the naming convention ✅" 